### ISSUE TITLE
Make utilities available through npm install

### ISSUE THREAD

**Issue by rzmahmood** [sekai-studio/starknet-libs#1]
Similar to https://github.com/0xs34n/starknet.js/blob/develop/README.md

It would be good to get some info on how we can use this library for the utilities.

Thank you!

**Comment by jag-lotus** [comment]
Hey @rzmahmood,

We are planning a big update that would include an npm repository availability. We are working with the StarkNet and ShardLabs teams to figure out nested repositories for easier use.

**Comment by jag-lotus** [comment]
Hey @rzmahmood,

The project has been migrated to [CairOpen](https://github.com/CairOpen/cairopen-contracts)

It is now easily accessible for your project using [Protostar](https://docs.swmansion.com/protostar/) and will soon be available for install using PyPI.

Thanks,
